### PR TITLE
Derive instance of Show for response wrappers.

### LINKED ISSUE #90: Make responses printable.
## Proposal:

Currently, the types such as `BsResponse` are black boxes. However, they seem trivial to show, since they are simply wrappers [of a type that has that instance][origin]. Possibly a derived instance can be added to the wrapper as well?

My use case is logging the responses precisely as they arrive for the purpose of debugging.

## Implementation:

```diff
diff --git a/Network/HTTP/Req.hs b/Network/HTTP/Req.hs
index 7b79601..166d91b 100644
--- a/Network/HTTP/Req.hs
+++ b/Network/HTTP/Req.hs
@@ -1560,7 +1560,7 @@ jsonResponse = Proxy

-- | Make a request and interpret the body of the response as a strict
-- 'ByteString'.
-newtype BsResponse = BsResponse (L.Response ByteString)
+newtype BsResponse = BsResponse (L.Response ByteString) deriving Show

instance HttpResponse BsResponse where
  type HttpResponseBody BsResponse = ByteString
```

[bs]: https://github.com/mrkkrp/req/blob/master/Network/HTTP/Req.hs#L1563
[origin]: https://hackage.haskell.org/package/http-client-0.7.0/docs/Network-HTTP-Client.html#t:Response

### PR DESCRIPTION
**Pull request by kindaro**
Resolve #90.

### CODE REVIEW

**Comment by mrkkrp** [comment]
Do you want me to release a new version with the change?

**Comment by kindaro** [comment]
@mrkkrp Would be good if you can!

**Comment by mrkkrp** [comment]
Published 3.3.0 on Hackage.

**Comment by kindaro** [comment]
Thanks!

**Pull request merged**
