### PR TITLE
Add compatibility with GHC 7.10.3.

### PR DESCRIPTION
**Pull request by ondrap**
I need to use this library with 7.10.3 - this patch makes it compile.

### CODE REVIEW

**Comment by ondrap** [comment]
It compiles for me... I'll try to make it compile on travis too....

**Comment by mrkkrp** [comment]
Hi, `bytestring` is not a "boot" library AFAIK, so it's possible to use `bytestring-0.10.8` with GHC 7.10.3. That said the library compiles fine with GHC 7.10.x and 7.8.x. What tool do you use? If you use stack, you'll need to add some libraries as `extra-deps`. If you use Cabal (as Travis does), we indeed need to find out what is wrong with its dependency resolution. When I released the library I made sure it works with GHC 8.0, GHC 7.10, and GHC 7.8:

https://travis-ci.org/mrkkrp/req/builds/175048027

**Comment by mrkkrp** [comment]
If you tell me more about your setup I'll try to help. I'll look into Travis failures today as well.

**Comment by ondrap** [comment]
Ok, so now in this PR this is what makes it compile for my 7.10.3 (it has bytestring 0.10.6). Somehow it still doesn't make it compile for your travis environment.

**Comment by mrkkrp** [comment]
Do you use stack?

**Comment by ondrap** [comment]
I have a native GHC installation 7.10.3 on MacOS - it compiles OK. I also have stack, lts-6.25 is OK as well.

**Comment by mrkkrp** [comment]
The library uses a couple of newer libs, all of them are compatible with older GHCs though. Apart from `bytestring`, newer `http-client` is needed, as it has quite a few breaking changes in version 0.5 that are not easy to repair even with CPP.

What happens if you use this `stack.yaml` file:

```yaml
resolver: lts-6.25
packages:
- '.'
extra-deps:
- bytestring-0.10.8.1
- http-client-0.5.4
- http-client-tls-0.3.3
```

**Comment by mrkkrp** [comment]
If this resolves your problem, please comment. If not, tell me what problem occurs with that `stack.yaml` setup.

**Comment by ondrap** [comment]
Ok, right - I didn't know I could override these basic packages. Seems to compile correctly, thanks.

**Comment by mrkkrp** [comment]
Yep, this is the way to use it for now, but overtime newer LTS will "just work" :-) Can we close this then?

**Comment by ondrap** [comment]
Yes, thank.

**Pull request closed without merging**
