### PR TITLE
add TextResponse, textResponse, fix grammar typos

### PR DESCRIPTION
**Pull request by ocramz**

### CODE REVIEW

**Comment by mrkkrp** [comment]
I have applied this as 3045fdcce364418251cb2d146636c369c57612c8. I added some more changes, let me know what you think. I'll a couple of new tests later.

**Comment by mrkkrp** [comment]
On a second thought I'm not sure these wrappers is a good idea. We probably should also add `ReqBodyText` and `ReqBodyLText` now for request bodies as well. Maybe it's best to leave encoding-decoding business to the end user? Although on the other hand these wrappers may be handy...

**Comment by mrkkrp** [comment]
I've been thinking about this and it looks like the existing set of response interpretations/request bodies is general and symmetric (i.e. byte strings are very general, JSON is a must have thing, etc.). Text can be easily obtained from byte string bodies, using any encoding with help of the various functions from `Data.Text.Encoding`. I think it's better to drop the text interpretations as they are a rather special case and only support one encoding---UTF-8. Looks like a lot of boilerplate to have only to support a not very popular functionality that can be achieved using existing byte string interpretations.

**Comment by ocramz** [comment]
On one hand it's true that this new functionality is just a special case of the ByteString interpretation, but I figured I'd add it to `req` since I found myself adding it in one of my projects the other day.

I hope you'll want to retain it for future versions.

**Comment by mrkkrp** [comment]
I thought about this for a couple of days, and decided to remove the interpretations for now. I checked what other similar libraries do and they seem to be OK without this feature. (I've already mentioned other arguments above.)

You can still define these interpretations in your project locally, so it shouldn't be a problem.

**Pull request closed without merging**
