### PR TITLE
Add reqWithMultipartFormData (#1)

### PR DESCRIPTION
**Pull request by joehillen**
While recommending `req` to [reddit](https://www.reddit.com/r/haskell/comments/5kdee8/why_is_wreq_not_in_the_stackage_nightlies/dbnih6p/?context=3), someone pointed out that `req` does not support Multipart Form Data. I was curious how difficult it would be to implement, and in the process, I implemented it. 🚀 

Unfortunately this use case does not fit with the existing `req` function because both generating the body and content-type requires `IO`. Rather than change the classes `HttpBody` and `RequestComponent` to accommodate this use case, I figured it would be easier to have a separate function.

I've broken up `req` into two internal functions `mkRequest` and `doRequest` in order to share code between `req` and `reqWithMultipartFormData`.

**Please note:** I have not actually tested this because I've never actually used mutlipart form data before, but since it's just glueing together pieces from `http-client` and it type-checks, I'm fairly certain this is correct.

I don't really plan to spend any more time on this since I personally don't need it, so if there are items that you disagree with, please merge it and make whatever changes you'd like.

@ondrap Can you please test this and see if it fits your needs?

### CODE REVIEW

**Comment by joehillen** [comment]
Adding a new `HttpBody` datatype was my initial approach, but it turned out that `getRequestBody` and `getRequestContentType` would need to be `IO` actions in order to render the `Part`s and generate the boundary for the `Content-Type` header. I think that's possible, but I wasn't sure how much you would want the library to be rewritten for this case.

**Comment by mrkkrp** [comment]
I'm not sure myself, need to try it, but I'll definitely get to releasing version 0.2.0 soon and this will be there is some form. We need to achieve partity with wreq :-D

**Comment by mrkkrp** [comment]
Found an alternative way to handle this: https://github.com/mrkkrp/req/pull/6.

**Comment by mrkkrp** [comment]
@ondrap, Support for multipart form data bodies has been added. I'll add OAuth authentication support today and release version 0.2.0. Please give it a try!

**Pull request closed without merging**
