### PR TITLE
Test with GHC 9.2.4 and GHC 9.4.1 + misc updates

### PR DESCRIPTION
**Pull request by mrkkrp**

### CODE REVIEW

**Comment by ysangkok** [comment]
Seems like this depends on

* vincenthz/hs-memory#93

**Comment by mrkkrp** [comment]
Yes, unfortunately the maintainer of this project is known to be exceptionally slow to merge PRs. Let's see how it goes...

**Comment by ysangkok** [comment]
@mrkkrp A new release of `memory` was made, could you please re-run the CI? It might pass now.

**Comment by mrkkrp** [comment]
Excellent! I'll bump the bound for `template-haskell`. Otherwise the published `req` should work fine with 9.4.1.

**Pull request merged**
