### PR TITLE
Add `parseUrl` for URLs with unknown schemes

### PR DESCRIPTION
**Pull request by waiting-for-dev**
References #48

### CODE REVIEW

**Comment by mrkkrp** [comment]
LGTM, but are you sure this helper is needed in the library? Seems quite trivial to "inline" the expression whenever is necessary.

**Comment by waiting-for-dev** [comment]
Hi @mrkkrp ,

thanks for your response. Not sure, but I think that it can be a common scenario when parsing an URL. If you already know which is the URL, probably you want to use `http` and `https` functions, but if you don't know it, probably you neither know its scheme.

If you don't like it, no worries. I also used it as a first chance to try with a Haskell contribution ;) But then, I think that at least `Http` and `Https` types should be exported so that people can write the type signature for the helper.

Besides, I don't know if it could exist a backward compatibility problem in the future with my current implementation. Using an `Either` means that in the case that other schemes are added later the API would be broken.

**Comment by tomjaguarpaw** [comment]
There is an invariant that a URL can match at most one of the `http` and `https` schemes.  This invariant can be encoded in the types and therefore should be, in my opinion.

**Comment by mrkkrp** [comment]
Isn't this already the case?

**Comment by tomjaguarpaw** [comment]
@mrkkrp It is the case in @waiting-for-dev's

```haskell
parseUrl :: ByteString -> Maybe (Either (Url 'Http, Option scheme) (Url 'Https, Option scheme))
```

It's not the case in the existing API.

**Comment by tomjaguarpaw** [comment]
In case it's not clear my comment was about why this PR provides something strictly better than currently exists.

**Comment by mrkkrp** [comment]
Let's merge this then.

**Comment by mrkkrp** [comment]
Published `req-1.2.0` with the change.

**Comment by waiting-for-dev** [comment]
Thanks for your quick action on this!

**Pull request merged**
